name: Audit pull request
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Waiting for 200 from the Netlify Preview
        uses: josephduffy/wait-for-netlify-action@v1
        id: wait-for-netlify-preview
        with:
          site_name: 'scriptified-test.netlify.app'
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'scriptified-test.netlify.app'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'